spring:
  application:
    name: CoCe-OrderService
    frontend-url: ${FRONTEND_URL:http://localhost:5173/order/}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/coce_orders}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${ORDER_SERVICE_PORT:8081}